///////////////////////////////////////////////////////////////////////////////////
/// OpenGL Image (gli.g-truc.net)
///
/// Copyright (c) 2008 - 2012 G-Truc Creation (www.g-truc.net)
/// Permission is hereby granted, free of charge, to any person obtaining a copy
/// of this software and associated documentation files (the "Software"), to deal
/// in the Software without restriction, including without limitation the rights
/// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
/// copies of the Software, and to permit persons to whom the Software is
/// furnished to do so, subject to the following conditions:
/// 
/// The above copyright notice and this permission notice shall be included in
/// all copies or substantial portions of the Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
/// THE SOFTWARE.
///
/// @ref core
/// @file gli/core/format.hpp
/// @date 2012-10-16 / 2012-10-16
/// @author Christophe Riccio
///////////////////////////////////////////////////////////////////////////////////

#pragma once

namespace gli
{
	enum format
	{
		FORMAT_INVALID = -1,

		// unorm formats
		FORMAT_R8_UNORM = 0, FORMAT_FIRST = FORMAT_R8_UNORM,
		FORMAT_RG8_UNORM,
		FORMAT_RGB8_UNORM,
		FORMAT_RGBA8_UNORM,

		FORMAT_R16_UNORM,
		FORMAT_RG16_UNORM,
		FORMAT_RGB16_UNORM,
		FORMAT_RGBA16_UNORM,

		FORMAT_RGB10A2_UNORM,

		// snorm formats
		FORMAT_R8_SNORM,
		FORMAT_RG8_SNORM,
		FORMAT_RGB8_SNORM,
		FORMAT_RGBA8_SNORM,

		FORMAT_R16_SNORM,
		FORMAT_RG16_SNORM,
		FORMAT_RGB16_SNORM,
		FORMAT_RGBA16_SNORM,

		// Unsigned integer formats
		FORMAT_R8U,
		FORMAT_RG8U,
		FORMAT_RGB8U,
		FORMAT_RGBA8U,

		FORMAT_R16U,
		FORMAT_RG16U,
		FORMAT_RGB16U,
		FORMAT_RGBA16U,

		FORMAT_R32U,
		FORMAT_RG32U,
		FORMAT_RGB32U,
		FORMAT_RGBA32U,

		FORMAT_RGB10A2U,

		// Signed integer formats
		FORMAT_R8I,
		FORMAT_RG8I,
		FORMAT_RGB8I,
		FORMAT_RGBA8I,

		FORMAT_R16I,
		FORMAT_RG16I,
		FORMAT_RGB16I,
		FORMAT_RGBA16I,

		FORMAT_R32I,
		FORMAT_RG32I,
		FORMAT_RGB32I,
		FORMAT_RGBA32I,

		// Floating formats
		FORMAT_R16F,
		FORMAT_RG16F,
		FORMAT_RGB16F,
		FORMAT_RGBA16F,

		FORMAT_R32F,
		FORMAT_RG32F,
		FORMAT_RGB32F,
		FORMAT_RGBA32F,

		// sRGB formats
		FORMAT_R8_SRGB,
		FORMAT_RG8_SRGB,
		FORMAT_RGB8_SRGB,
		FORMAT_RGBA8_SRGB,

		// Packed formats
		FORMAT_RGB9E5_UFLOAT,
		FORMAT_RG11B10_UFLOAT,
		FORMAT_RG3B2_UNORM,
		FORMAT_R5G6B5_UNORM,
		FORMAT_RGB5A1_UNORM,
		FORMAT_RGBA4_UNORM,

		// Swizzle formats
		FORMAT_BGR8_UNORM,
		FORMAT_BGRA8_UNORM,
		FORMAT_BGR8_SRGB,
		FORMAT_BGRA8_SRGB,

		// Luminance Alpha formats
		FORMAT_L8_UNORM,
		FORMAT_A8_UNORM,
		FORMAT_LA8_UNORM,
		FORMAT_L16_UNORM,
		FORMAT_A16_UNORM,
		FORMAT_LA16_UNORM,

		// Depth formats
		FORMAT_D16_UNORM,
		FORMAT_D24_UNORM,
		FORMAT_D24S8_UNORM,
		FORMAT_D32_UFLOAT,
		FORMAT_D32_UFLOAT_S8_UNORM,

		// Compressed formats
		FORMAT_RGB_DXT1_UNORM, FORMAT_COMPRESSED_FIRST = FORMAT_RGB_DXT1_UNORM,
		FORMAT_RGBA_DXT1_UNORM,
		FORMAT_RGBA_DXT3_UNORM,
		FORMAT_RGBA_DXT5_UNORM,
		FORMAT_R_ATI1N_UNORM,
		FORMAT_R_ATI1N_SNORM,
		FORMAT_RG_ATI2N_UNORM,
		FORMAT_RG_ATI2N_SNORM,
		FORMAT_RGB_BP_UFLOAT,
		FORMAT_RGB_BP_SFLOAT,
		FORMAT_RGB_BP_UNORM,
		FORMAT_RGB_PVRTC_4BPP_UNORM,
		FORMAT_RGB_PVRTC_2BPP_UNORM,
		FORMAT_RGBA_PVRTC_4BPP_UNORM,
		FORMAT_RGBA_PVRTC_2BPP_UNORM,
		FORMAT_RGBA_PVRTC2_4BPP_UNORM,
		FORMAT_RGBA_PVRTC2_2BPP_UNORM,
		FORMAT_RGB_ATC_UNORM,
		FORMAT_RGBA_ATC_EXPLICIT_UNORM,
		FORMAT_RGBA_ATC_INTERPOLATED_UNORM,
		FORMAT_RGB_ETC_UNORM,
		FORMAT_RGB_ETC2_UNORM,
		FORMAT_RGBA_ETC2_PUNCHTHROUGH_UNORM,
		FORMAT_RGBA_ETC2_UNORM,
		FORMAT_R11_EAC_UNORM,
		FORMAT_R11_EAC_SNORM,
		FORMAT_RG11_EAC_UNORM,
		FORMAT_RG11_EAC_SNORM,
		FORMAT_RGBA_ASTC4X4_UNORM,
		FORMAT_RGBA_ASTC5X4_UNORM,
		FORMAT_RGBA_ASTC5X5_UNORM,
		FORMAT_RGBA_ASTC6X5_UNORM,
		FORMAT_RGBA_ASTC6X6_UNORM,
		FORMAT_RGBA_ASTC8X5_UNORM,
		FORMAT_RGBA_ASTC8X6_UNORM,
		FORMAT_RGBA_ASTC8X8_UNORM,
		FORMAT_RGBA_ASTC10X5_UNORM,
		FORMAT_RGBA_ASTC10X6_UNORM,
		FORMAT_RGBA_ASTC10X8_UNORM,
		FORMAT_RGBA_ASTC10X10_UNORM,
		FORMAT_RGBA_ASTC12X10_UNORM,
		FORMAT_RGBA_ASTC12X12_UNORM,

		// Compressed sRGB formats
		FORMAT_RGB_DXT1_SRGB,
		FORMAT_RGB_ALPHA_DXT1_SRGB,
		FORMAT_RGB_ALPHA_DXT3_SRGB,
		FORMAT_RGB_ALPHA_DXT5_SRGB,
		FORMAT_RGB_BP_SRGB,
		FORMAT_RGB_PVRTC_2BPPV1_SRGB,
		FORMAT_RGB_PVRTC_4BPPV1_SRGB,
		FORMAT_RGBA_PVRTC_2BPP_SRGB,
		FORMAT_RGBA_PVRTC_4BPP_SRGB,
		FORMAT_RGBA_PVRTC2_2BPP_SRGB,
		FORMAT_RGBA_PVRTC2_4BPP_SRGB,
		FORMAT_RGB_ETC2_SRGB,
		FORMAT_RGBA_ETC2_PUNCHTHROUGH_SRGB,
		FORMAT_RGBA_ETC2_SRGB,
		FORMAT_RGBA_ASTC4X4_SRGB,
		FORMAT_RGBA_ASTC5X4_SRGB,
		FORMAT_RGBA_ASTC5X5_SRGB,
		FORMAT_RGBA_ASTC6X5_SRGB,
		FORMAT_RGBA_ASTC6X6_SRGB,
		FORMAT_RGBA_ASTC8X5_SRGB,
		FORMAT_RGBA_ASTC8X6_SRGB,
		FORMAT_RGBA_ASTC8X8_SRGB,
		FORMAT_RGBA_ASTC10X5_SRGB,
		FORMAT_RGBA_ASTC10X6_SRGB,
		FORMAT_RGBA_ASTC10X8_SRGB,
		FORMAT_RGBA_ASTC10X10_SRGB,
		FORMAT_RGBA_ASTC12X10_SRGB,
		FORMAT_RGBA_ASTC12X12_SRGB, FORMAT_COMPRESSED_LAST = FORMAT_RGBA_ASTC12X12_SRGB, FORMAT_LAST = FORMAT_RGBA_ASTC12X12_SRGB
	};

	enum
	{
		FORMAT_COUNT = FORMAT_LAST - FORMAT_FIRST + 1,
		FORMAT_COMPRESSED_COUNT = FORMAT_COMPRESSED_LAST - FORMAT_COMPRESSED_FIRST + 1
	};

	inline bool is_compressed(format const & Format)
	{
		return Format >= FORMAT_COMPRESSED_FIRST && Format <= FORMAT_COMPRESSED_LAST;
	}

	inline bool is_valid(format const & Format)
	{
		return Format >= FORMAT_FIRST && Format <= FORMAT_LAST;
	}

	std::uint32_t block_size(format const & Format);
	std::uint32_t block_dimensions_x(format const & Format);
	std::uint32_t block_dimensions_y(format const & Format);
	std::uint32_t block_dimensions_z(format const & Format);
	std::uint32_t component_count(format const & Format);
}//namespace gli

#include "format.inl"
